### DISCUSSION TITLE
ModuleNotFoundError in Docker

### DISCUSSION THREAD

**Discussion by giuqoob** [pymupdf/PyMuPDF#2351] [Looking for help] [answered]
I've been trying to take working code from my Windows PC to Docker without success. In Docker the installation process goes fine without error but later in the code I get this simple error
```
File "/code/table.py", line 35, in <module>
    import fitz
ModuleNotFoundError: No module named 'fitz'
```
Here's a snippet from my Dockerfile
```
FROM python:3.10
WORKDIR /code
COPY ./requirements.txt ./
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

# install PyMupdf
RUN pip install pymupdf

COPY . .

CMD ["python", "./run.py"]
```

And from my docker-compose.yml

```
build: .
container_name: ocr
command: python ./run.py
volumes:
  - .:/code
  - type: bind
    source: "C:/Program Files/Tesseract-OCR/tessdata"
    target: /code/tessdata
```

Any ideas? Anyone had success using PyMuPDF in Docker? Basically what my project is doing is taking some PDF files, moving them around and reading them. If reading them doesn't work, I do OCR first and go from there.
