### ISSUE TITLE
Installation failing while build.

### ISSUE THREAD

**Issue by RecNes** [pymupdf/PyMuPDF#1086]
## Describe the bug (mandatory)
Installing PyMuPDF on local is fine but Bitbucket pipeline is failing while build.

```
Collecting pymupdf==1.18.14 (from -r requirements.txt (line 242))
  Downloading https://files.pythonhosted.org/packages/41/f6/dbefe3d6949fa81fb7bcac9141e4345330d272724718ac5a6af78297498b/PyMuPDF-1.18.14.tar.gz (318kB)

Building wheels for collected packages: pymupdf
  Running setup.py bdist_wheel for pymupdf: started
  Running setup.py bdist_wheel for pymupdf: finished with status 'error'
  Complete output from command /usr/local/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-3qz4bc35/pymupdf/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-rkj0u8o7 --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/fitz
  copying fitz/__init__.py -> build/lib.linux-x86_64-3.6/fitz
  copying fitz/fitz.py -> build/lib.linux-x86_64-3.6/fitz
  copying fitz/utils.py -> build/lib.linux-x86_64-3.6/fitz
  copying fitz/__main__.py -> build/lib.linux-x86_64-3.6/fitz
  running build_ext
  building 'fitz._fitz' extension
  creating build/temp.linux-x86_64-3.6
  creating build/temp.linux-x86_64-3.6/fitz
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/include/mupdf -I/usr/local/include/mupdf -Imupdf/thirdparty/freetype/include -I/usr/include/freetype2 -I/usr/local/include/python3.6m -c fitz/fitz_wrap.c -o build/temp.linux-x86_64-3.6/fitz/fitz_wrap.o
  fitz/fitz_wrap.c:2754:18: fatal error: fitz.h: No such file or directory
   #include <fitz.h>
                    ^
  compilation terminated.
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for pymupdf
  Running setup.py clean for pymupdf
Failed to build pymupdf
```

## To Reproduce (mandatory)
Running pipeline with configuration below:

bitbucket-pipelines.yml:
```
image: python:3.6.5

pipelines:
  pull-requests:
    '**':
      - step:
          caches:
            - pip
          script: # Modify the commands below to build your repository.
            - pip install setuptools-scm==5.0.2
            - pip install -r requirements.txt
```

## Your configuration (mandatory)
 - Bitbucket Pipeline
 - python:3.6.5
 - pip version 10.0.1
 - pymupdf==1.18.14
